name: open-weather-auto-hub

services:
  flaskapp:
    container_name: flaskapp
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - '5000:5000'
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
  